
library(shiny)
library(shinydashboard)
library(tidyverse)
library(readr)
library(knitr)
library(ggplot2)
library(magrittr)
library(dplyr)
library(leaflet)
library(leaflet.extras)
library(maps)
library(plotly)
library(tidytext)
library(wordcloud)

crime_shiny <- read.csv("crime_shiny.csv")
crime_shiny$Year <- factor(crime_shiny$Year,levels = c("2015","2016","2017","2018","2019"))
motor_shiny <- read.csv("Motor_Incident.csv")
larceny_shiny <- read.csv("Larceny_Incident.csv")
assult_shiny <- read.csv("Simple_Assault.csv")
bookIcon <- makeIcon(iconUrl = "http://icons.iconarchive.com/icons/icons8/windows-8/512/Science-School-icon.png",
                     iconWidth = 38, iconHeight = 38)
crime_shiny$Description <- tolower(crime_shiny$Description)
test <- tibble(line = 1:length(crime_shiny$Description),text = crime_shiny$Description)
word <- test %>% unnest_tokens(word,text)

p<-ggplot(crime_shiny) + 
    geom_bar(aes(x = Year,y = ..prop..,group = 1)) + 
    facet_wrap(~ City, nrow = 4)
y <- ggplot(crime_shiny) + 
    geom_bar(aes(x = City, y = ..prop..,group=1)) + 
    facet_wrap(~ Year, nrow = 2)
pp <- ggplot(crime_shiny)+
    geom_bar(aes(x = City,fill = factor(Year)),stat = "count",position = "dodge")+
    coord_flip()
py <- ggplot(crime_shiny)+
    geom_bar(aes(x = Year,fill = factor(City)),stat = "count",position = "dodge")+
    coord_flip()
    
cities <- unique(crime_shiny$City)

# Define UI for application that draws a histogram

ui <- dashboardPage(
    dashboardHeader(title = "Crime Incident Reports"),
    dashboardSidebar(
        sidebarMenu(
            menuItem("Map",tabName = "map",icon = icon("map"),
                     menuSubItem("Cluster Map",tabName = "cluster"),
                     menuSubItem("Example:Motor Incident",tabName = "motor"),
                     menuSubItem("Example:Larceny Incident",tabName = "lar"),
                     menuSubItem("Example:Simple Assult",tabName = "as")),
            menuItem("City",tabName = "city",icon = icon("th"),
                     menuSubItem("City in General",tabName = "a"),
                     menuSubItem("City Detail",tabName = "b")),
            menuItem("Year",tabName = "year",icon = icon("th"),
                     menuSubItem("Year in General",tabName = "c"),
                     menuSubItem("Year Detail",tabName = "d")),
            menuItem("Text",tabName = "text",icon = icon("book",lib = "glyphicon"))
        )
    ),
    dashboardBody(
    tabItems(
        
        tabItem(tabName = "cluster",
                h2("Cluster Map for Crime Incident"),
                leafletOutput(outputId = "mymap"),
                wellPanel(h4(textOutput("intro")))
                ),
        
        tabItem(tabName = "motor",
                h2("Example: Motor Incident"),
                leafletOutput(outputId = "motormap"),
                wellPanel(h4(textOutput("con")))
               ),
        
        tabItem(tabName = "lar",
                h2("Example: Larceny Incident"),
                leafletOutput(outputId = "larmap"),
                wellPanel(h4(textOutput("con2")))
        ),
        
        tabItem(tabName = "as",
                h2("Example: Simple Assult"),
                leafletOutput(outputId = "assultmap"),
                wellPanel(h4(textOutput("con3")))
        ),
        
        tabItem(tabName = "a",
                h2("Crime Differ by Cities"),
                wellPanel(plotlyOutput("CityCount"))
                ),
                
        tabItem(tabName = "b",
                h2("Cities in Detail"),
                selectInput("City", "Select a City:", 
                            choices = unique(crime_shiny$City)),
                            
                wellPanel(h3(textOutput("caption")),
                            plotOutput("CityPlot")
                            )
        
                 ),
        
        tabItem(tabName = "c",
                h2("Crime Differ by Years"),
                wellPanel(plotlyOutput("YearCount"))
        ),
        
        tabItem(tabName = "d",
                h2("Years in Detail"),
                selectInput("Year", "Select a Year:", 
                            choices = unique(crime_shiny$Year)),
                
                wellPanel(h3(textOutput("cap")),
                          plotOutput("YearPlot")
                          )
                ),
        tabItem(tabName = "text",
                h2("Text Mining for Incident Discription"),
                wellPanel(plotOutput("TextPlot")))
    
)
)
)


# Define server logic required to draw a histogram
server <- function(input, output) {
    
    pal <- colorFactor(c("#999999", "#E69F00", "#56B4E9","#B2182B",
                         "#D6604D", "#F4A582", "#FDDBC7", "#D1E5F0",
                         "#92C5DE", "#4393C3", "#2166AC","#FFCC33"), domain = cities)
    
    IntroText <- reactive({
        print("The goal is to see the number of incidents happened in the Boston area. Maps are generated by
                   cluster maps in order to see how many incidents happened in a cluster,followed by some examples 
                   including: Motor Vehicle Accident, Larceny, and Simple Assault.
                   The examples were chosen to be the incidents that occurred most frequently.")
    })
    
    output$intro <- renderText({
        IntroText()
    })
    
    output$mymap <- renderLeaflet({
        leaflet(crime_shiny) %>% setView(lng = -71.0589, lat = 42.3601, zoom = 12) %>%
            addTiles() %>% 
            addAwesomeMarkers(data = crime_shiny,lng = ~Longtitude,lat = ~Latitude,clusterOptions = T)%>% 
            addMarkers(lng =  -71.099688,lat = 42.349634,icon = bookIcon)
    })
    
    output$motormap <- renderLeaflet({
        leaflet(motor_shiny) %>% setView(lng = -71.0589, lat = 42.3601, zoom = 12) %>%
            addTiles() %>% addMarkers(lng =  -71.099688,lat = 42.349634,icon = bookIcon) %>% # Mark BU
            addMarkers(data = motor_shiny[1:100,],lng = ~Longtitude,lat = ~Latitude)
    })
    
    ConMText <- reactive({
        print("There were some motor incidents close to Boston University Area observed from the map. 
        Based on the 100 observations, motor incidents most frequently happened in Dorchester.")
    })
    
    output$con <- renderText({
        ConMText()
    })
    
    output$larmap <- renderLeaflet({
        leaflet(larceny_shiny) %>% setView(lng = -71.0589, lat = 42.3601, zoom = 12) %>%
            addTiles() %>% addMarkers(lng =  -71.099688,lat = 42.349634,icon = bookIcon) %>% 
            addMarkers(data = larceny_shiny[1:100,],lng = ~Longtitude,lat = ~Latitude)
    })
    
    ConLText <- reactive({
        print("There were some larceny happened near Boston Univerity Area. Based on the 100 observations, larceny most 
              frequently happened in Back Bay as well as South End areas. This maybe because these areas are relatively
              rich.")
    })
    
    output$con2 <- renderText({
        ConLText()
    })
    
    output$assultmap <- renderLeaflet({
        leaflet(assult_shiny) %>% setView(lng = -71.0589, lat = 42.3601, zoom = 12) %>%
            addTiles() %>% addMarkers(lng =  -71.099688,lat = 42.349634,icon = bookIcon) %>% 
            addMarkers(data = assult_shiny[1:100,],lng = ~Longtitude,lat = ~Latitude)
    })
    
    ConAText <- reactive({
        print("From both the map and the 100 observations, assult incidents mostly happened to the east of Boston area.
              Several were happened close to the Boston Univeristy Area but generally not many occured around university
              distric.")
    })
    
    output$con3 <- renderText({
        ConAText()
    })
    
    output$CityCount <- renderPlotly({
        plotly_build(pp)
    })
    
    CityText <- reactive({
        paste("Selected City:", input$City)
    })
    
    output$caption <- renderText({
        CityText()
    })

    output$CityPlot <- renderPlot({
        # plot the bar chart by Cities
        p$data <- p$data %>% group_by(City) %>% filter(City == input$City)
        p
    })
    
    output$YearCount <- renderPlotly({
        plotly_build(py)
    })
    
    YearText <- reactive({
        paste("Selected Year:", input$Year)
    })
    
    output$cap <- renderText({
        YearText()
    })
    
    output$YearPlot <- renderPlot({
        # plot the bar chart by Years
        y$data <- y$data %>% group_by(Year) %>% filter(Year == input$Year)
        y
    })
    
    output$TextPlot <- renderPlot({
        word %>% anti_join(stop_words) %>% count(word) %>% with(wordcloud(word, n, max.words = 100))
    })
}

# Run the application 
shinyApp(ui = ui, server = server)
